SUMMARY = "summary"
LIVE = "live"

INSTRU_ID = "instrument_code"
VOLUME = "volume_traded"
MARKET_PRICE = "market_price"
DOLLAR_CHANGE = "dollar_change"
TRADE_TIME = "trade_time"
STATUS = "status"
PERCENT_CHANGE = "percentage_change"

IS_LISTED = "is_listed"
LAST_UPDATED_DATE = "last_updated_date"
INSTRUMENT_NAME = "instrument_name"
INSTRUMENT_CODE = "instrument_code"
SYMBOL = "symbol"
CURRENCY = "currency"
SECTOR = "sector"
TYPE = "type"
WEBSITE = "website"
MARKET = "market"

LISTED = "Listed"
DE_LISTED = "De-listed"

STOCK_ID = "stock"
AMOUNT = "amount"
PAYMENT_DUE = "payment_date"
DIVIDEND_URL = "url"
PAYMENTS = "payments"
DIVIDENDS = "dividends"
TRADE_INFO = "trade_info"

STOCK_SPLIT = "stock_split"
EXECUTION_DATE = "execution_date"
RECORD_DATE = "record_date"
EXECUTION_DATES = "execution_dates"
STOCK_SPLIT_URL = "url"
STOCK_CORPORATE_ACTION_URL = "corporate_action_url"

JA_TIMEZONE = "America/Jamaica"
